/*{"k":"1.7.2","created":"2014-03-24T15:10:40Z","version":"25377918","mac":"1:5f492129a06a3bfb0940d5af9722b6a2f6cd59d581a8a100e36eeb5ac34602ed"}*/
/*
 * For font license information, see the CSS file loaded by this JavaScript.
 */
;(function(window,document,undefined){
var j=!0,k=null,l=!1;function m(a){return function(){return this[a]}}var aa=this;function ba(a,b){var c=a.split("."),d=aa;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&void 0!==b?d[e]=b:d=d[e]?d[e]:d[e]={}}function ca(a,b,c){return a.call.apply(a.bind,arguments)}
function da(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function n(a,b,c){n=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ca:da;return n.apply(k,arguments)}var ea=Date.now||function(){return+new Date};
function fa(a,b){this.Y=a;this.P=b||a;this.F=this.P.document}fa.prototype.createElement=function(a,b,c){a=this.F.createElement(a);if(b)for(var d in b)b.hasOwnProperty(d)&&("style"==d?a.style.cssText=b[d]:a.setAttribute(d,b[d]));c&&a.appendChild(this.F.createTextNode(c));return a};function q(a,b,c){a=a.F.getElementsByTagName(b)[0];a||(a=document.documentElement);a&&a.lastChild&&a.insertBefore(c,a.lastChild)}function ga(a,b){function c(){a.F.body?b():setTimeout(c,0)}c()}
function r(a,b){for(var c=a.className.split(/\s+/),d=0,e=c.length;d<e;d++)if(c[d]==b)return;c.push(b);a.className=c.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}function s(a,b){for(var c=a.className.split(/\s+/),d=[],e=0,f=c.length;e<f;e++)c[e]!=b&&d.push(c[e]);a.className=d.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}function ha(a,b){for(var c=a.className.split(/\s+/),d=0,e=c.length;d<e;d++)if(c[d]==b)return j;return l}
function ia(a){var b=a.P.location.protocol;"about:"==b&&(b=a.Y.location.protocol);return"https:"==b?"https:":"http:"}
function ja(a,b,c){var d=a.F.getElementsByTagName("head")[0];if(d){var e=a.createElement("script",{src:b}),f=l;e.onload=e.onreadystatechange=function(){if(!f&&(!this.readyState||"loaded"==this.readyState||"complete"==this.readyState))f=j,c&&c(k),e.onload=e.onreadystatechange=k,"HEAD"==e.parentNode.tagName&&d.removeChild(e)};d.appendChild(e);window.setTimeout(function(){f||(f=j,c&&c(Error("Script load timeout")))},5E3)}}function t(a,b,c){this.Oa=a;this.aa=b;this.Na=c}
ba("internalWebfont.BrowserInfo",t);t.prototype.Ba=m("Oa");t.prototype.hasWebFontSupport=t.prototype.Ba;t.prototype.Ca=m("aa");t.prototype.hasWebKitFallbackBug=t.prototype.Ca;t.prototype.Da=m("Na");t.prototype.hasWebKitMetricsBug=t.prototype.Da;function u(a,b,c,d){this.e=a!=k?a:k;this.m=b!=k?b:k;this.D=c!=k?c:k;this.j=d!=k?d:k}var ka=/^([0-9]+)(?:[\._-]([0-9]+))?(?:[\._-]([0-9]+))?(?:[\._+-]?(.*))?$/;
function v(a,b){return a.e>b.e||a.e===b.e&&a.m>b.m||a.e===b.e&&a.m===b.m&&a.D>b.D?1:a.e<b.e||a.e===b.e&&a.m<b.m||a.e===b.e&&a.m===b.m&&a.D<b.D?-1:0}function w(a,b){return 0===v(a,b)||1===v(a,b)}u.prototype.toString=function(){return[this.e,this.m||"",this.D||"",this.j||""].join("")};
function x(a){a=ka.exec(a);var b=k,c=k,d=k,e=k;a&&(a[1]!==k&&a[1]&&(b=parseInt(a[1],10)),a[2]!==k&&a[2]&&(c=parseInt(a[2],10)),a[3]!==k&&a[3]&&(d=parseInt(a[3],10)),a[4]!==k&&a[4]&&(e=/^[0-9]+$/.test(a[4])?parseInt(a[4],10):a[4]));return new u(b,c,d,e)}function y(a,b,c,d,e,f,g,h,p,K,D){this.Q=a;this.n=b;this.Ma=c;this.v=d;this.A=e;this.ra=f;this.k=g;this.h=h;this.Ia=p;this.N=K;this.t=D}ba("internalWebfont.UserAgent",y);y.prototype.getName=m("Q");y.prototype.getName=y.prototype.getName;
y.prototype.Aa=m("Ma");y.prototype.getVersion=y.prototype.Aa;y.prototype.wa=m("v");y.prototype.getEngine=y.prototype.wa;y.prototype.xa=m("ra");y.prototype.getEngineVersion=y.prototype.xa;y.prototype.ya=m("k");y.prototype.getPlatform=y.prototype.ya;y.prototype.za=m("Ia");y.prototype.getPlatformVersion=y.prototype.za;y.prototype.va=m("N");y.prototype.getDocumentMode=y.prototype.va;y.prototype.ua=m("t");y.prototype.getBrowserInfo=y.prototype.ua;function na(a,b){this.c=a;this.M=b}
var oa=new y("Unknown",new u,"Unknown","Unknown",new u,"Unknown","Unknown",new u,"Unknown",void 0,new t(l,l,l));
na.prototype.parse=function(){var a;if(-1!=this.c.indexOf("MSIE")||-1!=this.c.indexOf("Trident/")){a=z(this);var b=A(this),c=x(b),d=k,e=k,f=k,g=k,h=B(this.c,/Trident\/([\d\w\.]+)/,1),p=E(this.M),d=-1!=this.c.indexOf("MSIE")?B(this.c,/MSIE ([\d\w\.]+)/,1):B(this.c,/rv:([\d\w\.]+)/,1),e=x(d);""!=h?(f="Trident",g=x(h)):(f="Unknown",g=new u,h="Unknown");a=new y("MSIE",e,d,f,g,h,a,c,b,p,new t("Windows"==a&&6<=e.e||"Windows Phone"==a&&8<=c.e,l,l))}else if(-1!=this.c.indexOf("Opera"))a:if(a="Unknown",b=
B(this.c,/Presto\/([\d\w\.]+)/,1),c=x(b),d=A(this),e=x(d),f=E(this.M),c.e!==k?a="Presto":(-1!=this.c.indexOf("Gecko")&&(a="Gecko"),b=B(this.c,/rv:([^\)]+)/,1),c=x(b)),-1!=this.c.indexOf("Opera Mini/"))g=B(this.c,/Opera Mini\/([\d\.]+)/,1),h=x(g),a=new y("OperaMini",h,g,a,c,b,z(this),e,d,f,new t(l,l,l));else{if(-1!=this.c.indexOf("Version/")&&(g=B(this.c,/Version\/([\d\.]+)/,1),h=x(g),h.e!==k)){a=new y("Opera",h,g,a,c,b,z(this),e,d,f,new t(10<=h.e,l,l));break a}g=B(this.c,/Opera[\/ ]([\d\.]+)/,1);
h=x(g);a=h.e!==k?new y("Opera",h,g,a,c,b,z(this),e,d,f,new t(10<=h.e,l,l)):new y("Opera",new u,"Unknown",a,c,b,z(this),e,d,f,new t(l,l,l))}else/OPR\/[\d.]+/.test(this.c)?a=pa(this):/AppleWeb(K|k)it/.test(this.c)?a=pa(this):-1!=this.c.indexOf("Gecko")?(a="Unknown",b=new u,c="Unknown",d=A(this),e=x(d),f=l,-1!=this.c.indexOf("Firefox")?(a="Firefox",c=B(this.c,/Firefox\/([\d\w\.]+)/,1),b=x(c),f=3<=b.e&&5<=b.m):-1!=this.c.indexOf("Mozilla")&&(a="Mozilla"),g=B(this.c,/rv:([^\)]+)/,1),h=x(g),f||(f=1<h.e||
1==h.e&&9<h.m||1==h.e&&9==h.m&&2<=h.D||g.match(/1\.9\.1b[123]/)!=k||g.match(/1\.9\.1\.[\d\.]+/)!=k),a=new y(a,b,c,"Gecko",h,g,z(this),e,d,E(this.M),new t(f,l,l))):a=oa;return a};function z(a){var b=B(a.c,/(iPod|iPad|iPhone|Android|Windows Phone|BB\d{2}|BlackBerry)/,1);if(""!=b)return/BB\d{2}/.test(b)&&(b="BlackBerry"),b;a=B(a.c,/(Linux|Mac_PowerPC|Macintosh|Windows|CrOS)/,1);return""!=a?("Mac_PowerPC"==a&&(a="Macintosh"),a):"Unknown"}
function A(a){var b=B(a.c,/(OS X|Windows NT|Android) ([^;)]+)/,2);if(b||(b=B(a.c,/Windows Phone( OS)? ([^;)]+)/,2))||(b=B(a.c,/(iPhone )?OS ([\d_]+)/,2)))return b;if(b=B(a.c,/(?:Linux|CrOS) ([^;)]+)/,1))for(var b=b.split(/\s/),c=0;c<b.length;c+=1)if(/^[\d\._]+$/.test(b[c]))return b[c];return(a=B(a.c,/(BB\d{2}|BlackBerry).*?Version\/([^\s]*)/,2))?a:"Unknown"}
function pa(a){var b=z(a),c=A(a),d=x(c),e=B(a.c,/AppleWeb(?:K|k)it\/([\d\.\+]+)/,1),f=x(e),g="Unknown",h=new u,p="Unknown",K=l;/OPR\/[\d.]+/.test(a.c)?g="Opera":-1!=a.c.indexOf("Chrome")||-1!=a.c.indexOf("CrMo")||-1!=a.c.indexOf("CriOS")?g="Chrome":/Silk\/\d/.test(a.c)?g="Silk":"BlackBerry"==b||"Android"==b?g="BuiltinBrowser":-1!=a.c.indexOf("PhantomJS")?g="PhantomJS":-1!=a.c.indexOf("Safari")?g="Safari":-1!=a.c.indexOf("AdobeAIR")&&(g="AdobeAIR");"BuiltinBrowser"==g?p="Unknown":"Silk"==g?p=B(a.c,
/Silk\/([\d\._]+)/,1):"Chrome"==g?p=B(a.c,/(Chrome|CrMo|CriOS)\/([\d\.]+)/,2):-1!=a.c.indexOf("Version/")?p=B(a.c,/Version\/([\d\.\w]+)/,1):"AdobeAIR"==g?p=B(a.c,/AdobeAIR\/([\d\.]+)/,1):"Opera"==g?p=B(a.c,/OPR\/([\d.]+)/,1):"PhantomJS"==g&&(p=B(a.c,/PhantomJS\/([\d.]+)/,1));h=x(p);K="AdobeAIR"==g?2<h.e||2==h.e&&5<=h.m:"BlackBerry"==b?10<=d.e:"Android"==b?2<d.e||2==d.e&&1<d.m:526<=f.e||525<=f.e&&13<=f.m;return new y(g,h,p,"AppleWebKit",f,e,b,d,c,E(a.M),new t(K,536>f.e||536==f.e&&11>f.m,"iPhone"==
b||"iPad"==b||"iPod"==b||"Macintosh"==b))}function B(a,b,c){return(a=a.match(b))&&a[c]?a[c]:""}function E(a){if(a.documentMode)return a.documentMode}function qa(a){this.Ga=a||"-"}qa.prototype.j=function(a){for(var b=[],c=0;c<arguments.length;c++)b.push(arguments[c].replace(/[\W_]+/g,"").toLowerCase());return b.join(this.Ga)};function ra(a,b,c){this.g=a;this.l=b;this.T=c;this.q="wf";this.p=new qa("-")}
function sa(a){s(a.l,a.p.j(a.q,"loading"));ha(a.l,a.p.j(a.q,"active"))||r(a.l,a.p.j(a.q,"inactive"));F(a,"inactive")}function F(a,b,c){if(a.T[b])if(c)a.T[b](c.getName(),G(c));else a.T[b]()}function I(a,b){this.Q=a;this.ba=4;this.R="n";var c=(b||"n4").match(/^([nio])([1-9])$/i);c&&(this.R=c[1],this.ba=parseInt(c[2],10))}I.prototype.getName=m("Q");function G(a){return a.R+a.ba}function J(a,b){this.g=a;this.J=b;this.z=this.g.createElement("span",{"aria-hidden":"true"},this.J)}
function ta(a,b){var c;c=[];for(var d=b.Q.split(/,\s*/),e=0;e<d.length;e++){var f=d[e].replace(/['"]/g,"");-1==f.indexOf(" ")?c.push(f):c.push("'"+f+"'")}c=c.join(",");d="normal";e=b.ba+"00";"o"===b.R?d="oblique":"i"===b.R&&(d="italic");a.z.style.cssText="position:absolute;top:-999px;left:-999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;white-space:nowrap;font-family:"+c+";"+("font-style:"+d+";font-weight:"+e+";")}
function ua(a){q(a.g,"body",a.z)}J.prototype.remove=function(){var a=this.z;a.parentNode&&a.parentNode.removeChild(a)};function va(a,b,c,d,e,f,g,h){this.ca=a;this.Ea=b;this.g=c;this.w=d;this.J=h||"BESbswy";this.t=e;this.K={};this.Z=f||5E3;this.la=g||k;this.I=this.H=k;a=new J(this.g,this.J);ua(a);for(var p in L)L.hasOwnProperty(p)&&(ta(a,new I(L[p],G(this.w))),this.K[L[p]]=a.z.offsetWidth);a.remove()}var L={Va:"serif",Ua:"sans-serif",Ra:"monospace"};
va.prototype.start=function(){this.H=new J(this.g,this.J);ua(this.H);this.I=new J(this.g,this.J);ua(this.I);this.Ka=ea();ta(this.H,new I(this.w.getName()+",serif",G(this.w)));ta(this.I,new I(this.w.getName()+",sans-serif",G(this.w)));wa(this)};function xa(a,b,c){for(var d in L)if(L.hasOwnProperty(d)&&b===a.K[L[d]]&&c===a.K[L[d]])return j;return l}
function wa(a){var b=a.H.z.offsetWidth,c=a.I.z.offsetWidth;b===a.K.serif&&c===a.K["sans-serif"]||a.t.aa&&xa(a,b,c)?ea()-a.Ka>=a.Z?a.t.aa&&xa(a,b,c)&&(a.la===k||a.la.hasOwnProperty(a.w.getName()))?ya(a,a.ca):ya(a,a.Ea):setTimeout(n(function(){wa(this)},a),25):ya(a,a.ca)}function ya(a,b){a.H.remove();a.I.remove();b(a.w)}function M(a,b,c,d){this.g=b;this.B=c;this.V=0;this.oa=this.ka=l;this.Z=d;this.t=a.t}
M.prototype.$=function(a,b,c,d){if(0===a.length&&d)sa(this.B);else{this.V+=a.length;d&&(this.ka=d);for(d=0;d<a.length;d++){var e=a[d],f=b[e.getName()],g=this.B,h=e;r(g.l,g.p.j(g.q,h.getName(),G(h).toString(),"loading"));F(g,"fontloading",h);(new va(n(this.sa,this),n(this.ta,this),this.g,e,this.t,this.Z,c,f)).start()}}};
M.prototype.sa=function(a){var b=this.B;s(b.l,b.p.j(b.q,a.getName(),G(a).toString(),"loading"));s(b.l,b.p.j(b.q,a.getName(),G(a).toString(),"inactive"));r(b.l,b.p.j(b.q,a.getName(),G(a).toString(),"active"));F(b,"fontactive",a);this.oa=j;za(this)};M.prototype.ta=function(a){var b=this.B;s(b.l,b.p.j(b.q,a.getName(),G(a).toString(),"loading"));ha(b.l,b.p.j(b.q,a.getName(),G(a).toString(),"active"))||r(b.l,b.p.j(b.q,a.getName(),G(a).toString(),"inactive"));F(b,"fontinactive",a);za(this)};
function za(a){0==--a.V&&a.ka&&(a.oa?(a=a.B,s(a.l,a.p.j(a.q,"loading")),s(a.l,a.p.j(a.q,"inactive")),r(a.l,a.p.j(a.q,"active")),F(a,"active")):sa(a.B))}function N(a,b){this.Ja=a;this.ga=b}function Aa(a){for(var b=a.Ja.join(","),c=[],d=0;d<a.ga.length;d++){var e=a.ga[d];c.push(e.name+":"+e.value+";")}return b+"{"+c.join("")+"}"}function Ba(a){this.g=a}Ba.prototype.toString=function(){return encodeURIComponent(this.g.P.location.hostname||this.g.Y.location.hostname)};
function Ca(a,b){this.r=a;this.o=b}Ca.prototype.toString=function(){for(var a=[],b=0;b<this.o.length;b++)for(var c=this.o[b],d=c.C(),c=c.C(this.r),e=0;e<d.length;e++){var f;a:{for(f=0;f<c.length;f++)if(d[e]===c[f]){f=j;break a}f=l}a.push(f?1:0)}a=a.join("");a=a.replace(/^0+/,"");b=[];for(d=a.length;0<d;d-=4)c=a.slice(0>d-4?0:d-4,d),b.unshift(parseInt(c,2).toString(16));return b.join("")};function O(a){this.La=a}
O.prototype.j=function(a,b){var c=b||{},d=this.La.replace(/\{\/?([^*}]*)(\*?)\}/g,function(a,b,d){return d&&c[b]?"/"+c[b].join("/"):c[b]||""});d.match(/^\/\//)&&(d=(a?"https:":"http:")+d);return d.replace(/\/*\?*($|\?)/,"$1")};function P(a,b,c,d){this.G=a;this.O=b;this.Ya=c;this.Za=d;this.ia={};this.ha={}}P.prototype.C=function(a){return a?(this.ia[a]||this.O).slice(0):this.O.slice(0)};P.prototype.$=function(a,b,c){var d=[],e={};Da(this,b,d,e);a(d,e,c)};
function Da(a,b,c,d){c.push(a.G);d[a.G]=a.C(b);a=a.ha[b]||[];for(b=0;b<a.length;b++){for(var e=a[b],f=e.G,g=l,h=0;h<c.length;h++)c[h]==f&&(g=j);g||(c.push(f),d[f]=e.C())}}function Ea(a,b){this.G=a;this.O=b}Ea.prototype.C=m("O");function Fa(){this.qa=this.Pa=this.L=this.W=this.Fa=j}function R(a){return"Windows"===a.k}function S(a){return R(a)&&0===v(a.h,new u(5,1))||R(a)&&0===v(a.h,new u(5,2))||R(a)&&0===v(a.h,new u(6,0))||R(a)&&w(a.h,new u(6,1))}
function T(a){return"Macintosh"===a.k&&(w(a.h,new u(10,4))||a.h.e===k)}function Ga(a,b){return b.Fa&&("iPhone"===a.k||"iPod"===a.k)}function Ha(a,b){return Ga(a,b)&&w(a.h,new u(4,2))&&-1===v(a.h,new u(5))}function Ia(a,b){return b.W&&"iPad"===a.k&&w(a.h,new u(4,2))&&-1===v(a.h,new u(5))}function U(a,b){return b.L&&"Android"===a.k}function Ja(a,b){return U(a,b)&&w(a.h,new u(2,2))&&-1===v(a.h,new u(3,1))}function Ka(a,b){return U(a,b)&&w(a.h,new u(3,1))&&-1===v(a.h,new u(4,1))}
function V(a){return"Linux"===a.k||"Ubuntu"===a.k}function La(a){return"Gecko"===a.v&&0===v(a.A,new u(1,9,1))&&!/^b[1-3]$/.test(a.A.j||"")}function Ma(a){return"Safari"===a.getName()&&"AppleWebKit"===a.v||"Unknown"===a.getName()&&"AppleWebKit"===a.v&&("iPhone"===a.k||"iPad"===a.k||"iPod"===a.k)}function Na(a){return"Safari"===a.getName()&&"AppleWebKit"===a.v&&w(a.A,new u(525,13))&&-1===v(a.A,new u(534,50))}function Oa(a){return"Opera"===a.getName()&&w(a.n,new u(10,54))&&-1===v(a.n,new u(11,10))}
function Qa(a){return"BuiltinBrowser"===a.getName()}function Ra(a){this.na=a}function Sa(a,b){return b}
var Ta={Sa:"a",Ta:"b",Xa:"d",Wa:"f",Qa:"i"},Ua={a:function(a,b){return Na(a)&&S(a)||Qa(a)&&(Ja(a,b)||U(a,b)&&w(a.h,new u(4,1)))||b.L&&"Silk"===a.getName()&&-1===v(a.n,new u(2))&&(Ja(a,b)||T)||b.L&&"Silk"===a.getName()&&w(a.n,new u(2))&&U(a,b)&&w(a.h,new u(4,1))||Ma(a)&&(Ia(a,b)||Ha(a,b))||La(a)&&(S(a)||V(a))||Oa(a)&&(S(a)||V(a))||("Chrome"===a.getName()&&1===v(a.n,new u(4,0,249))&&-1===v(a.n,new u(6))||0===v(a.n,new u(4,0,249))&&(a.n.j===k||4<=a.n.j))&&(S(a)||V(a)||T(a))||"Chrome"===a.getName()&&
w(a.n,new u(6))&&(Ia(a,b)||Ha(a,b))||"AdobeAIR"===a.getName()&&w(a.n,new u(2,5))&&(R(a)&&a.h.e===k||V(a))},b:function(a){return La(a)&&T(a)||Na(a)&&T(a)||Oa(a)&&T(a)||"AdobeAIR"===a.getName()&&w(a.n,new u(2,5))&&T(a)},d:function(a,b){return"Chrome"===a.getName()&&w(a.n,new u(6))&&(S(a)||V(a)||T(a)||U(a,b)||"CrOS"===a.k||b.W&&"iPad"===a.k&&w(a.h,new u(5))||Ga(a,b)&&w(a.h,new u(5)))||"Gecko"===a.v&&1===v(a.A,new u(1,9,1))&&(S(a)||V(a)||T(a)||U(a,b))||"Safari"===a.getName()&&("AppleWebKit"===a.v&&w(a.A,
new u(534,50)))&&(S(a)||T(a))||Ma(a)&&(b.W&&"iPad"===a.k&&w(a.h,new u(5))||Ga(a,b)&&w(a.h,new u(5)))||"Opera"===a.getName()&&w(a.n,new u(11,10))&&(S(a)||V(a)||T(a)||U(a,b))||"MSIE"===a.getName()&&9<=a.N&&(R(a)&&w(a.h,new u(6,1))||R(a)&&0===v(a.h,new u(6,0)))||"MSIE"===a.getName()&&b.Pa&&"Windows Phone"===a.k&&w(a.h,new u(8))||Qa(a)&&b.qa&&"BlackBerry"===a.k&&w(a.h,new u(10))},f:function(a,b){return Qa(a)&&Ka(a,b)||b.L&&"Silk"===a.getName()&&w(a.n,new u(2))&&(Ka(a,b)||V(a))},i:function(a){return"MSIE"===
a.getName()&&(w(a.n,new u(6,0))&&(void 0===a.N||9>a.N))&&S(a)}};function Va(a,b){var c=b||new Fa,d;for(d in Ta){var e=Ta[d];if(Ua[e](a,c))return e}return k}var Wa={};
Wa.i=new Ra(function(a,b,c){for(var d=0;d<b.length;d+=1){var e=b[d],f=a.replace(/(-1|-2)$/,"").slice(0,28)+"-"+e;c.push(new Ea(f,[e]))}a={};for(e=0;e<b.length;e++)c=b[e],d=c.charAt(1),(a[d]||(a[d]=[])).push(c);c=[[4,3,2,1,5,6,7,8,9],[7,8,9,6,5,4,3,2,1]];d=[];for(e=0;e<c.length;e++)for(var f=c[e],g=0;g<f.length;g++){var h=f[g];if(a[h]){d=d.concat(a[h]);break}}c=d;d={};a=[];for(e=0;e<c.length;e++)f=c[e],d[f]||(d[f]=j,a.push(f));c=[];for(d=0;d<b.length;d++){e=b[d];for(f=0;f<a.length;f++)g=a[f],g==e&&
c.push(g)}return c});var W={};W.a=W.b=W.d=function(){return[]};W.f=function(a){return[new Ba(a)]};W.i=function(a,b,c){return[new Ba(a),new Ca(b,c)]};function X(a){this.g=a;this.ea=this.c=this.r=k;this.o=[];this.u=[];this.pa=this.U=k}X.prototype.supportsConfiguredBrowser=function(){return!!this.r};
X.prototype.init=function(){if(0<this.u.length){for(var a=[],b=0;b<this.u.length;b++)a.push(Aa(this.u[b]));var b=this.g,a=a.join(""),c=this.g.createElement("style");c.setAttribute("type","text/css");c.styleSheet?c.styleSheet.cssText=a:c.appendChild(document.createTextNode(a));q(b,"head",c)}};
X.prototype.load=function(a,b,c){if(this.r){for(var d=Wa[this.r]||new Ra(Sa),e=0;e<this.o.length;e++){for(var f=this.o[e],g=this.r,h=d,p=[],K=f.G.split(",")[0].replace(/"|'/g,""),D=f.C(),Q=p,C=void 0,H=[],Pa={},la=0;la<D.length;la++)C=D[la],0<C.length&&!Pa[C]&&(Pa[C]=j,H.push(C));D=H;h=h.na?h.na(K,D,Q):D;f.ia[g]=h;f.ha[g]=p}if(this.U){d=W[this.r](this.g,this.r,this.o);e=this.r;f=[];for(g=0;g<d.length;g++)f.push(d[g].toString());d={format:e,extras:f};c&&(d.contextPath=c);d=this.U.j("https:"===ia(this.g),
d);c=this.g;var d=c.createElement("link",{rel:"stylesheet",href:d}),Z=l;d.onload=function(){Z||(Z=j)};d.onerror=function(){Z||(Z=j)};q(c,"head",d)}if(a){var ma=this,eb=this.r;ga(this.g,function(){for(var c=0;c<ma.o.length;c++)ma.o[c].$(a,eb,b&&c==ma.o.length-1)})}}};X.prototype.collectFontFamilies=function(a,b){if(this.r)for(var c=0;c<this.o.length;c++)Da(this.o[c],this.r,a,b)};
X.prototype.performOptionalActions=function(){if(this.X){var a=this,b=this.c,c=this.g;ga(this.g,function(){var d=a.X;if(d.ma){var e=window.__adobewebfontsappname__,e=e?e.toString().substr(0,20):"",d=d.ma.j("https:"===ia(c),{host:encodeURIComponent(c.P.location.hostname||c.Y.location.hostname),app:encodeURIComponent(e),_:(+new Date).toString()}),f=new Image(1,1);f.src=d;f.onload=function(){f.onload=k}}d=a.X;d.da&&(d=d.da.j(b,c),q(c,"body",d))})}};
function Xa(a,b,c,d){this.Ha=a;this.fa=k;this.g=b;this.c=c;this.l=d;this.s=[]}Xa.prototype.S=function(a){this.s.push(a)};Xa.prototype.load=function(a,b){var c=a,d=b||{};if("string"==typeof c)c=[c];else if(!c||!c.length)d=c||{},c=[];if(c.length)for(var e=this,f=c.length,g=0;g<c.length;g++){var h=this.Ha.j("https:"===ia(this.g),{id:encodeURIComponent(c[g])});ja(this.g,h,function(){0==--f&&Ya(e,d)})}else Ya(this,d)};
function Ya(a,b){if(0!=a.s.length){a.fa=b.contextPath||k;for(var c=new ra(a.g,a.l,b),d=l,e=0;e<a.s.length;e++)a.s[e].init(),d=d||a.s[e].supportsConfiguredBrowser();if(d){r(c.l,c.p.j(c.q,"loading"));F(c,"loading");for(var f=new M(a.c,a.g,c,b.timeout),c=function(a,b,c){for(var d=[],e=0;e<a.length;e+=1){var Q=a[e];if(b[Q])for(var C=b[Q],H=0;H<C.length;H+=1)d.push(new I(Q,C[H]));else d.push(new I(Q))}f.$(d,{},k,c)},d=0;d<a.s.length;d++)e=a.s[d],e.supportsConfiguredBrowser()&&(e.load(c,d==a.s.length-1,
a.fa),e.performOptionalActions(window))}else sa(c);a.s=[]}}function Za(a){this.ja=a;this.s=[]}Za.prototype.S=function(a){this.s.push(a)};
Za.prototype.load=function(){var a=this.ja.__webfonttypekitmodule__;if(a)for(var b=0;b<this.s.length;b++){var c=this.s[b],d=a[c.pa];d&&d(function(a,b,d){a=[];b={};var h=(new na(navigator.userAgent,document)).parse(),p=c;p.c=h;p.r=Va(p.c,p.ea);c.supportsConfiguredBrowser()&&(c.init(),c.load(k),c.collectFontFamilies(a,b),c.performOptionalActions(window));d(c.supportsConfiguredBrowser(),a,b)})}};var $a=(new na(navigator.userAgent,document)).parse();window.Typekit||(window.Typekit={});
if(!window.Typekit.load){var Y=new Xa(new O("//fonts.mathworks.com/{id}.js"),new fa(window),$a,document.documentElement),ab=new Za(window);window.Typekit.load=function(){Y.load.apply(Y,arguments)};window.Typekit.addKit=function(){Y.S.apply(Y,arguments)}}var bb=k,cb,$,bb=new O("//p.typekit.net/p.gif?a=712561&f=2032.5545.10879.10880.10881.10882.10884.10885.18153&h={host}&ht=sh&k=xvy5baa&s=1&_={_}");cb=new function(){var a=bb;this.da=k;this.ma=a};$=new X(new fa(window));$.pa="xvy5baa";$.U=new O("//fonts.mathworks.com/k/xvy5baa-{format}.css?3bb2a6e53c9684ffdc9a99f11f5b2a6259e9e580e4938fcb487bcb48ad765cb4c66326ede94ac48d6ede67e4500a24e97a0591ac31cb9a79f653770995b73fcab179c8843e167d4d294efffce20684477e3030043617caba214c58b6f154839e39f8538e92cdd7798839d1a59e4d2b0791bbe6e783a84640f50c6e8f631ac5fd6e2928747046e8d3c8014f4e612066d47cd2f6460236d5af8067bf5be13b5d402fc9b57daa008f4648c576b0daffc4a09719f26748e4d12162f1841b44cd6114f823631817018292249f9424158262729aedfc9a7eaad686e19704ecf794505a5bf58346b86674958b71b58f71e596df71adc85eb06870a8aa3fa53e996a1fc9a87139ba5f47c506b20f3f5af733a35e32b903f3ea3ad28c5600e222fef219fa6d117c0d627897884abcb24d233482306c08ad5732c7ff2a2566cd5fa9554fc45a683e4492630af7837ac201efe374b4410a1ebb0f78147daed230fd70b646914a1bf60c1e5586d424a9779647a2ccd561f26b04a124f9");
$.X=cb;$.o.push(new P("museo-slab",["n7"]));$.o.push(new P("futura-pt","n4 i4 n5 i5 n7 i7".split(" ")));$.o.push(new P("automate",["n7"]));$.o.push(new P("minion-pro-subhead",["n4"]));$.u.push(new N([".tk-museo-slab"],[{name:"font-family",value:'"museo-slab",serif'}]));$.u.push(new N([".tk-futura-pt"],[{name:"font-family",value:'"futura-pt","Arial","Helvetica",sans-serif'}]));$.u.push(new N([".tk-automate"],[{name:"font-family",value:'"automate",sans-serif'}]));
$.u.push(new N([".tk-minion-pro-subhead"],[{name:"font-family",value:'"minion-pro-subhead",serif'}]));var db;if(db=ab)db=!!ab.ja.__webfonttypekitmodule__;db?(ab.S($),ab.load()):($.c=$a,$.r=Va($.c,$.ea),window.Typekit.addKit($));
})(this,document);
